### ISSUE TITLE
List的scroll-bottom事件不触发，持续报错

### ISSUE THREAD

**Issue by YujiaCheng1996** [jd-opensource/nutui#2206]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-vue version（nutui-vue 版本）

4.0.4

### Vue version（vue 版本）
3.2.47

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
19.8.1

### Browser and its version（浏览器及其版本）
Chrome110

### System and its version（系统及其版本）
Win11

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 19.8.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\Administrator\AppData\Local\pnpm\yarn.CMD
      npm: 9.6.1 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/list)

### Steps to reproduce（重现步骤）
任意写一个list，传入container-height，内容超出范围滚动

### What is expected?（期望的结果是什么？）
触发对应事件

### What is actually happening?（实际的结果是什么？）
滚动时持续报错：
caught (in promise) TypeError: Cannot read properties of undefined (reading 'bottom')
    at getStartIndex (List.js:170:1)
    at _callee2$ (List.js:186:1)
    at tryCatch (regeneratorRuntime.js:44:1)
    at Generator.eval (regeneratorRuntime.js:125:1)
    at Generator.eval [as next] (regeneratorRuntime.js:69:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at eval (asyncToGenerator.js:27:1)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js:19:1)
g

### Remarks（补充说明）
scroll-up/down也是如此

**Comment by virgoone** [comment]
同样遇到，4.0.3和4.0.4版本一样，外部容器未设置样式，如果设置container-height为外部容器的高度，报上述错误，如果不设置，则不滚动，也不会触发scroll-up/down

**Comment by vhrers** [comment]
同样遇到，滑动到底部就会触发错误：
caught (in promise) TypeError: Cannot read properties of undefined (reading 'bottom')

**Comment by dyubo2005** [comment]
顶起来，查看源码发现是 listData 的props中listData 的watch 没有触发导致虚拟列表没有初始化

**Comment by bo-tea** [comment]
一样的问题  小程序+vue3+taro3.6.2
ui版本4.0.0和.5都尝试过

**Comment by YujiaCheng1996** [comment]
现在用的taro3.6.5和nutui4.0.6，还是报错，并且转向使用taro的virtual-list也是在小程序端不触发scroll事件，h5端正常。总之taro的vue3版就没有正常支持虚拟列表的组件了。

**Comment by dyubo2005** [comment]
> 你好 @YujiaCheng1996, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/eh6ck?resolutionWidth=414&resolutionHeight=736) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

是 taro init name, 选择Vue3 + NutUI4.0 创建的项目中出现的问题，codesandbox 自己创建的并不能复现。原因未知。
